### PR TITLE
Fix/wait issue

### PR DESCRIPTION
**Pull request by IgorSasovets**

### CODE REVIEW

**Comment by IgorSasovets** [comment]
@lilletech , I fixed tests and now all works as expected (at least on my machine). Try it and provide feedback

**Comment by lilletech** [comment]
Hi @IgorSasovets , thanks for the fix for this sample application.
I've tested on my real project ( i can't share the source for confidentiality reasons ), but when i return to the application i got 

Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  - Failed: Timed out waiting for asynchronous Angular tasks to finish after 30 seconds. This may be because the current page is not an Angular application. Please see the FAQ for more details: https://github.com/angular/protractor/blob/master/docs/timeouts.md#waiting-for-angular

it's really strange because i don't have any http loading or background task. My app load in 2 sec

capture2
capture3

Do you see another reason that could cause such behavior ?

**Comment by IgorSasovets** [comment]
There are a lot of reasons which can cause such behavior. Sometimes we have deal with browser load itself. Protractor takes too much time to run browser especially if you're using `directConnect` option. But it happens not so frequently. Another reason is protractor interaction with app. Depending on components that your application uses there may be problems with it. I faced with it when was writing tests for ng5 app which used angular-material. I had almost the same errors and fixed it using custom synchronization.

**Comment by lilletech** [comment]
Ok, it's was i was doing for a previous project . i wrote a service that set value in a variable "ready". http Interceptor and dom changes modify this value. 
The test launches was under java (junit + selenium) and the drivers call js to read this variable before each element search.

I was switching to protractor to have the same behaviour !

I continue to investigate. Thanks a lot

**Comment by IgorSasovets** [comment]
@lilletech , I know that it can cause additional problems and requires more time to implement but for now we have to deal with it somehow)) Good luck) P.R. I had problems with Actions class functions in Fifrefox and only way to handle it was to create [custom lib](https://github.com/IgorSasovets/protractor-firefox-support).

**Pull request merged**
